/* Replace with your SQL commands */
CREATE TABLE IF NOT EXISTS Users(
id INT AUTO_INCREMENT PRIMARY KEY, 
username VARCHAR(50) NOT NULL, 
password VARCHAR(60) NOT NULL, 
name NVARCHAR(50) NOT NULL, 
surname NVARCHAR(50) NOT NULL, 
email NVARCHAR(255) NOT NULL,
role ENUM('REGULAR', 'CREATOR') DEFAULT 'REGULAR');