/* Replace with your SQL commands */
CREATE TABLE IF NOT EXISTS Courses(
id INT AUTO_INCREMENT PRIMARY KEY, 
owner_id INT NOT NULL, 
title NVARCHAR(100) NOT NULL,
language ENUM('POLISH', 'ENGLISH') DEFAULT 'POLISH',
dateStart DATE NOT NULL,
dateFinish DATE NOT NULL,
hoursStart TIME NOT NULL,
hoursFinish TIME NOT NULL,
hoursTimes SMALLINT NOT NULL,
level ENUM('BEGINNER', 'INTERMEDIATE', 'EXPERT') DEFAULT 'BEGINNER',
location NVARCHAR(100) NOT NULL,
trainer NVARCHAR(120) NOT NULL,
FOREIGN KEY(owner_id) REFERENCES Users(id) ON DELETE CASCADE
);